### PR TITLE
Initial commit for database schema.

### LINKED ISSUE #12: set up database
The skeleton is already in place with https://github.com/thirdknife/scoutingapp/issues/1. The next step is to fill in the schema as described in 
* https://docs.google.com/document/d/1hUt03tnKQ5kv_-Fdsi6AuzX4g3XStW8WWEjqaqVch5E/edit#heading=h.g9q42sa4ufxi
* https://app.eraser.io/workspace/mbuZda5ThydsiMCuhi4A

Since we're using SQLite and there is no expected interaction between data from each scout, we're going to use a sqlite database for each scout. In the server, we'll keep an expiring cache from a user token to their database. When they first log in, we'll load their database and add an entry to the map. The expiring part is so that the database gets closed after a period of inactivity (~6 hours?).

Pro:
* Each person's information is guaranteed to be separate, barring egregious bugs in our implementation.
* If it becomes necessary, it's easy to shard work across multiple servers by giving each one a chunk of the database files and having a router to send traffic to the right server.
* Easy to make incremental backups without copying all of the data from everyone. We'll only need to add back ups for databases that have changed in the past day.
* Very easy to fully delete a user's data or find all of it for GDPR requests.

Con:
* Need to manage multiple files
* Potential latency when first loading a scout's information, though the network request latency ought to be far more than reading the database from disk.
* If we want to share data between scouts in the future, it will require a migration.

In order for the server to be able to find the database for a given login, either:
* we need a separate database to track Scout information and store the database file name. This is probably a good choice. The only downside is that it's a bit of additional work to set up and query this table.
* the files would need to be named in a special way. This would allow a login request to directly calculate the database filename.
  * For example, the name could be a hash of some unchanging Scout field (e.g. their username).
  * We could use the username directly, but that could result in unexpected issues if we aren't careful about sanitizing user inputs.

### PR DESCRIPTION
**Pull request by Omustardo**
The schema is from https://app.eraser.io/workspace/mbuZda5ThydsiMCuhi4A

### CODE REVIEW

File: database/database_generated_tests.go [hunk 1]
```diff
@@ -0,0 +1,195 @@
...
+import (
+	"testing"
+	"time"
+
+	"gorm.io/driver/sqlite"
+	"gorm.io/gorm"
+)
+
+func setupTestDB(t *testing.T) *gorm.DB {
+	db, err := gorm.Open(sqlite.Open("file::memory:?cache=shared"), &gorm.Config{})
```
Comment (thirdknife) [inline database/database_generated_tests.go:13]: nice

**Review by thirdknife — APPROVED** [review]

File: database/database.go [hunk 2]
```diff
@@ -1,62 +1,39 @@
...
-}
-
-// New creates a new database at the given path. It fails if there is already a file at that path.
-func New(path string) (*Database, error) {
-	_, err := os.Stat(path)
-	if os.IsNotExist(err) {
-		// The file not existing is good. This method creates it.
-	} else {
-		return nil, fmt.Errorf("database file %q already exists", path)
+		path = "file::memory:?cache=shared"
```
Comment (thirdknife) [inline database/database.go:14]: I guess this can be swapped with a database connection if postgres is needed?

Comment (Omustardo) [reply database/database.go:14]: Yeah - "GORM officially supports the databases MySQL, PostgreSQL, SQLite, SQL Server, and TiDB"

https://gorm.io/docs/connecting_to_the_database.html#PostgreSQL
